- hosts: local
  connection: local
  gather_facts: False 
  vars:
    pem_path: /root/.ssh/ansible.pem
    lab_id: host2-0004
    image: ami-0323c3dd2da7fb37d
    instance_type: t2.medium
    volumes:
    - device_name: /dev/xvda
      volume_size: 20
    ssh_user: ec2-user
    count: 1
    aws_tags:
      Name: lab-host2

  vars_files:
  - /root/ansible/playbooks/aws_keys.yml 

  roles:
    - create_lab_network
    - create_ec2_instance

  tasks:

    - name: Add hosts group temporary inventory group with pem path
      add_host:
        name: "{{ ec2.instances[0].public_ip }}"
        groups: dynamic_hosts
        ansible_ssh_private_key_file: '{{ pem_path }}'
        ansible_ssh_user: "{{ ssh_user }}"
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: dynamic_hosts
  remote_user: ec2-user
  become: yes
  gather_facts: True

  pre_tasks:
  - name: Print distribution 
    debug:
      msg: "The OS Family is {{ ansible_distribution }}"

  roles:
    - install_graphite
    - install_grafana
    - install_collectd


